#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

require_pattern() {
  local file="$1"
  local pattern="$2"
  local label="$3"

  if ! grep -q "$pattern" "$ROOT_DIR/$file"; then
    echo "FAIL missing $label in $file: $pattern" >&2
    exit 1
  fi
}

require_pattern "TEXnologia/App/AppModel.swift" "isEditableTextFile" "text file routing"
require_pattern "TEXnologia/App/AppModel.swift" "isGeneratedTextPreviewFile" "generated file preview routing"
require_pattern "TEXnologia/App/AppModel.swift" "loadReadOnlyPreview" "read-only generated file preview"
require_pattern "TEXnologia/App/AppModel.swift" "maxEditableBytes" "large editable file guard"
require_pattern "TEXnologia/App/AppModel.swift" '"sty"' "sty remains editable"
require_pattern "TEXnologia/App/AppModel.swift" '"bib"' "bib remains editable"
require_pattern "TEXnologia/App/AppModel.swift" '"log", "aux", "bbl", "blg", "toc", "out", "fls"' "generated extensions are preview-only"
require_pattern "TEXnologia/App/AppModel.swift" '"json"' "JSON routing"
require_pattern "TEXnologia/App/AppModel.swift" "prettyPrintedJSONIfPossible" "JSON pretty print"
require_pattern "TEXnologia/App/AppModel.swift" "case \"pdf\"" "PDF routing"
require_pattern "TEXnologia/App/AppModel.swift" "case \"png\", \"jpg\", \"jpeg\"" "image routing"

require_pattern "TEXnologia/App/MainWindowView.swift" "CenterPaneView" "center pane dispatcher"
require_pattern "TEXnologia/App/MainWindowView.swift" "CompileOptionsControl" "attached compile options control"
require_pattern "TEXnologia/App/MainWindowView.swift" "compileBlue" "muted blue compile button"
require_pattern "TEXnologia/App/MainWindowView.swift" ".frame(width: 109)" "compact compile control"
require_pattern "TEXnologia/App/MainWindowView.swift" "Button(\"Compile\"" "compile button wording"
require_pattern "TEXnologia/App/MainWindowView.swift" "Compile Settings" "compile settings dropdown tooltip"
require_pattern "TEXnologia/App/MainWindowView.swift" "CompileSettingsPopover" "single-arrow compile settings popover"
require_pattern "TEXnologia/App/MainWindowView.swift" "Text(\"Engine\")" "compile dropdown engine section"
require_pattern "TEXnologia/App/MainWindowView.swift" "Text(\"TeX Live Year\")" "compile dropdown TeX year section"
require_pattern "TEXnologia/App/MainWindowView.swift" "settings.defaultEngine = engine" "compile dropdown engine persistence"
require_pattern "TEXnologia/App/MainWindowView.swift" "settings.toolchainYear = year" "compile dropdown year persistence"
require_pattern "TEXnologia/App/MainWindowView.swift" "HistoryPopover" "history popover"
require_pattern "TEXnologia/App/MainWindowView.swift" "clock.arrow.circlepath" "history icon button"
require_pattern "TEXnologia/App/MainWindowView.swift" "square.and.arrow.down" "PDF export icon button"
require_pattern "TEXnologia/App/MainWindowView.swift" "Export PDF" "PDF export tooltip"
require_pattern "TEXnologia/App/AppModel.swift" "exportFocusedPDF" "focused PDF export action"
require_pattern "TEXnologia/App/AppModel.swift" "NSSavePanel" "PDF export save panel"
require_pattern "TEXnologia/App/MainWindowView.swift" "RightPreviewPane" "right preview pane"
require_pattern "TEXnologia/App/MainWindowView.swift" "VSplitView" "split preview pane"
require_pattern "TEXnologia/App/MainWindowView.swift" "@Binding var isSplit" "preview-local split control"
require_pattern "TEXnologia/Core/CoreModels.swift" "PreviewPaneID" "preview pane focus model"
require_pattern "TEXnologia/App/AppModel.swift" "focusedPreviewPane" "focused preview pane state"
require_pattern "TEXnologia/App/AppModel.swift" "showInFocusedPreview" "focused preview routing"
require_pattern "TEXnologia/App/AppModel.swift" "editorFileURL" "editor file separated from explorer selection"
require_pattern "TEXnologia/App/AppModel.swift" "prepareEditorForPreviewSelection" "image/pdf selection keeps source editor"
require_pattern "TEXnologia/App/AppModel.swift" "Editor kept" "preview selection editor preservation status"
require_pattern "TEXnologia/App/AppModel.swift" "try editorText.write(to: editorFileURL" "save uses editor file, not preview selection"
require_pattern "TEXnologia/App/MainWindowView.swift" "focusedPane" "preview focus binding"
require_pattern "TEXnologia/App/MainWindowView.swift" "Color.orange" "focused preview orange indicator"
require_pattern "TEXnologia/App/MainWindowView.swift" ".stroke(isFocused ? Color.orange" "focused preview border"
require_pattern "TEXnologia/App/MainWindowView.swift" "GeometryReader" "responsive welcome layout"
require_pattern "TEXnologia/App/MainWindowView.swift" "ScrollView(.vertical)" "welcome overflow protection"
require_pattern "TEXnologia/App/MainWindowView.swift" "compact(proxy)" "compact welcome sizing"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ProjectSessionsSidebarView" "multi-session explorer"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ScrollView(.vertical)" "custom explorer scroll layout"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ExplorerIconButtonStyle" "modern explorer icon buttons"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ExplorerStyle.sidebarBackground" "soft explorer sidebar background"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ExplorerSectionHeader(title: \"구조\")" "styled outline section"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ExplorerSectionHeader(title: \"인용\")" "styled citations section"
require_pattern "TEXnologia/App/MainWindowView.swift" "outlineFileURL: appModel.editorFileURL" "outline follows currently open editor file"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "currentFileOutline" "outline filters to current file"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "allowedCommands: Set<String> = \\[\"section\", \"subsection\", \"paragraph\"\\]" "outline only shows section subsection paragraph"
require_pattern "TEXnologia/ProjectIndexing/ProjectIndexer.swift" "section|subsection|paragraph" "indexer captures only requested outline commands"
require_pattern "TEXnologia/ProjectIndexing/ProjectIndex.swift" "var command: String" "outline stores LaTeX command type"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "RoundedRectangle(cornerRadius: 10" "pill explorer row selection"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "EmptyExplorerState" "styled empty explorer state"
require_pattern "TEXnologia/App/MainWindowView.swift" "SessionTabBar" "session tab bar"
require_pattern "TEXnologia/App/MainWindowView.swift" "New Session" "new session button"
require_pattern "TEXnologia/App/MainWindowView.swift" "Close Session" "close session context menu"
require_pattern "TEXnologia/App/AppModel.swift" "closeSession" "session close model action"
require_pattern "TEXnologia/App/AppModel.swift" "sessions.remove" "session-only close removal"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "Use as Main File" "main file context menu"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "InlineRenameTextField" "inline explorer rename"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "PendingCreationRow" "blank inline file creation"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "creationDraft = \"\"" "new file starts with empty input"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "commitCreation(proposedName" "new file commit receives typed filename"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "Data().write(to: destination" "new file creates real empty file on disk"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "doCommandBy commandSelector" "inline field handles Enter through AppKit field editor"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "commit?(textView.string)" "inline field commits the current typed text"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "renameDraft = url.lastPathComponent" "rename edits full filename"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "renameStemSelectionRange" "rename selects stem by default"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ExplorerKeyboardMonitor" "explorer keyboard shortcuts"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ProjectDirectoryMonitor" "external Finder change watcher"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "FSEventStreamCreate" "recursive macOS project directory monitoring"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "kFSEventStreamCreateFlagFileEvents" "file-level external change events"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "restartDirectoryMonitor" "watcher restarts on root changes"
require_pattern "TEXnologia/App/AppModel.swift" "refreshProjectFromDisk" "external refresh preserves editor text"
require_pattern "TEXnologia/App/MainWindowView.swift" "onExternalProjectChange: appModel.refreshProjectFromDisk" "external watcher refresh wiring"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "deletePermanently" "actual filesystem delete"
if grep -q 'New TeX File' "$ROOT_DIR/TEXnologia/ProjectIndexing/ProjectSidebarView.swift"; then
  echo "FAIL new file action should not force TeX wording" >&2
  exit 1
fi
if grep -q 'untitled.tex' "$ROOT_DIR/TEXnologia/ProjectIndexing/ProjectSidebarView.swift"; then
  echo "FAIL new file action should not prefill .tex extension" >&2
  exit 1
fi
require_pattern "TEXnologia/App/AppModel.swift" "saveSelectedFileAndBuildIfNeeded" "command-s compile on save"
require_pattern "TEXnologia/App/TEXnologiaApp.swift" "Save and Compile" "save menu compile wording"
require_pattern "TEXnologia/App/AppModel.swift" "isEditorSaved" "editor saved-state model"
require_pattern "TEXnologia/App/AppModel.swift" "fileSaveStates" "explorer save-state model"
require_pattern "TEXnologia/App/AppModel.swift" "updateEditorText" "editor edits mark file dirty"
require_pattern "TEXnologia/App/AppModel.swift" "fileSaveStates\\[editorFileURL\\] = .dirty" "modified editor file is orange"
require_pattern "TEXnologia/App/AppModel.swift" "fileSaveStates\\[editorFileURL\\] = .saved" "saved editor file is green"
require_pattern "TEXnologia/App/AppModel.swift" "moveExplorerSaveState" "rename migrates explorer save state"
require_pattern "TEXnologia/App/AppModel.swift" "removeExplorerSaveState" "delete removes explorer save state"
require_pattern "TEXnologia/App/AppModel.swift" "pruneMissingExplorerSaveStates" "missing files prune stale save state"
require_pattern "TEXnologia/App/AppModel.swift" "movedURL" "directory rename rewrites descendant save state"
require_pattern "TEXnologia/App/AppModel.swift" "markEditorClean(fileURL: editorFileURL, text: editorText)" "save marks editor clean"
require_pattern "TEXnologia/App/MainWindowView.swift" "EditorStatusHeader" "editor saved-state header"
require_pattern "TEXnologia/App/MainWindowView.swift" "checkmark.square.fill" "saved check indicator"
require_pattern "TEXnologia/App/MainWindowView.swift" "tray.and.arrow.down" "toolbar save button"
require_pattern "TEXnologia/App/MainWindowView.swift" "set: { appModel.updateEditorText" "editor binding uses dirty-state setter"
require_pattern "TEXnologia/App/MainWindowView.swift" "onMoveFile: appModel.moveExplorerSaveState" "sidebar rename wired to app save state"
require_pattern "TEXnologia/App/MainWindowView.swift" "onDeleteFile: appModel.removeExplorerSaveState" "sidebar delete wired to app save state"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "saveStates: \\[URL: ExplorerSaveState\\]" "sidebar receives save states"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "ExplorerSaveStateDot" "explorer save-state dot"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "descendantStates.contains(.dirty)" "directories show dirty descendant state"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "descendantStates.contains(.saved)" "directories show saved descendant state"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "onMoveFile(url, destination)" "rename reports moved file"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "onMoveFile(source, destination)" "drag-drop move reports moved file"
require_pattern "TEXnologia/ProjectIndexing/ProjectSidebarView.swift" "onDeleteFile(url)" "delete reports removed file"
require_pattern "TEXnologia/App/MainWindowView.swift" "appModel.openProjectPanel" "welcome/menu open action remains"
if grep -q 'Label("Open"' "$ROOT_DIR/TEXnologia/App/MainWindowView.swift"; then
  echo "FAIL toolbar Open button should not be present" >&2
  exit 1
fi
if grep -q 'Label("Zip"' "$ROOT_DIR/TEXnologia/App/MainWindowView.swift"; then
  echo "FAIL toolbar Zip button should not be present" >&2
  exit 1
fi
require_pattern "TEXnologia/App/MainWindowView.swift" "ReadOnlyTextPreviewPane" "read-only text preview pane"
require_pattern "TEXnologia/App/MainWindowView.swift" "doc.text.magnifyingglass" "generated text preview icon"
require_pattern "TEXnologia/App/MainWindowView.swift" "PDFPaneView(documentURL: url)" "center PDF rendering"
require_pattern "TEXnologia/App/MainWindowView.swift" "ImagePreviewPane" "image preview pane"
require_pattern "TEXnologia/App/MainWindowView.swift" ".task(id: fileURL)" "async image preview loading"
require_pattern "TEXnologia/App/MainWindowView.swift" "editorFileURL: appModel.editorFileURL" "center editor uses dedicated editor file"
require_pattern "TEXnologia/App/MainWindowView.swift" "syntaxMode: editorFileURL?.editorSyntaxMode" "syntax mode not tied to preview selection"
require_pattern "TEXnologia/App/MainWindowView.swift" "max(proxy.size.width - 40" "image preview constrained to pane width"
require_pattern "TEXnologia/App/MainWindowView.swift" ".fixedSize(horizontal: false, vertical: false)" "image preview does not request window growth"
require_pattern "TEXnologia/App/MainWindowView.swift" "Open Externally" "external open action"
require_pattern "TEXnologia/App/MainWindowView.swift" "Reveal in Finder" "finder reveal action"

require_pattern "TEXnologia/IssueNavigator/IssueNavigatorView.swift" "IssueDockView" "collapsed issue dock"
require_pattern "TEXnologia/IssueNavigator/IssueNavigatorView.swift" "Show Issues" "manual issue expansion"
require_pattern "TEXnologia/IssueNavigator/IssueNavigatorView.swift" "Raw Log" "manual raw log disclosure"
require_pattern "TEXnologia/IssueNavigator/IssueNavigatorView.swift" "Jump to Source" "issue source jump"
require_pattern "TEXnologia/App/MainWindowView.swift" "shouldShowIssueDock" "issue dock hidden when no actionable issues"
require_pattern "TEXnologia/App/MainWindowView.swift" "issuePanelExpanded ? 260 : 36" "collapsed issue panel height"
require_pattern "TEXnologia/App/MainWindowView.swift" ".clipped()" "issue dock clipping guard"

require_pattern "TEXnologia/App/TEXnologiaApp.swift" "toggleFullScreen" "full screen shortcut"
require_pattern "TEXnologia/App/TEXnologiaApp.swift" ".command, .control" "Control-Command-F shortcut"

require_pattern "TEXnologia/Preferences/PreferencesView.swift" "TabView" "preferences tabs"
require_pattern "TEXnologia/App/AppModel.swift" "SettingsStore.save" "settings persistence"
require_pattern "Package.swift" "TEXnologia" "renamed executable product"
require_pattern "scripts/build_app_bundle.sh" "TEXnologia.app" "renamed app bundle"
require_pattern "TEXnologia/App/MainWindowView.swift" "TEXnologia" "renamed visible app title"
require_pattern "TEXnologia/BuildSystem/BuildConfiguration.swift" ".texnologia-build" "renamed build directory"
require_pattern "TEXnologia/BuildSystem/BuildConfiguration.swift" "TexToolchainYear" "TeX Live year model"
require_pattern "TEXnologia/BuildSystem/BuildConfiguration.swift" "texLive2024" "default TeX Live 2024 support"
require_pattern "TEXnologia/BuildSystem/BuildConfiguration.swift" "texLive2025" "TeX Live 2025 support"
require_pattern "TEXnologia/Preferences/AppSettings.swift" "toolchainYear: .texLive2024" "default pdflatex 2024 setting"
require_pattern "TEXnologia/BuildSystem/LatexBuildService.swift" "/usr/local/texlive/" "year-specific TeX path lookup"

require_pattern "TEXnologia/Editor/LatexSyntaxHighlighter.swift" "isSpellCheckExcluded" "LaTeX spellcheck exclusion test"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "shouldSetSpellingState" "LaTeX spellcheck veto"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "setSpellingState(0" "clearing LaTeX spelling markers"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "CheckingType.grammar" "English grammar checking"
require_pattern "TEXnologia/Editor/LatexSyntaxHighlighter.swift" "latexOnlyCommandNames" "citation/reference spellcheck filtering"
require_pattern "TEXnologia/Editor/LatexSyntaxHighlighter.swift" "BibTokenizer" "BibTeX syntax highlighting"
require_pattern "TEXnologia/Editor/LatexSyntaxHighlighter.swift" "applyCommentTokensLast" "comment highlighting precedence"
require_pattern "TEXnologia/Editor/LatexSyntaxHighlighter.swift" "overlapsCommentRange" "comment overlap guard"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "scheduleHighlight" "debounced editor highlighting"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "allowsNonContiguousLayout = true" "non-contiguous editor layout"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "LineNumberRulerView" "editor line numbers"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "hasVerticalRuler = true" "line number ruler enabled"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "lineNumberGutterWidth: CGFloat = 74" "line number gutter width"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "override var requiredThickness" "line number ruler reserves space"
require_pattern "TEXnologia/Editor/LaTeXEditorView.swift" "NSColor.separatorColor" "line number gutter separator"
require_pattern "TEXnologia/PDFViewer/PDFPaneView.swift" "NonResizingPDFView" "PDF preview does not request window growth"
require_pattern "TEXnologia/PDFViewer/PDFPaneView.swift" "PDFDocument(url:" "async PDF document loading"
require_pattern "TEXnologia/App/MainWindowView.swift" "editorSyntaxMode" "extension-based syntax routing"

echo "PASS feature contracts"
